name: ci
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
    - name: &checkout Checkout
      uses: actions/checkout@v2
    - name: &install-node Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - name: &cache Cache Node.js modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{matrix.node-version}}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-${{matrix.node-version}}-
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: &install-dependencies Install dependencies
      run: npm ci
    - name: Build
      run: COVERAGE=1 npm run all
    - name: Upload coverage
      run: npx codecov
  build-nodes:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x, 12.x]

    steps:
    - *checkout
    - *install-node
    - *cache
    - *install-dependencies
    - name: Build
      run: npm run all
  build-platforms:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [14.x]

    steps:
    - *checkout
    - *install-node
    - *cache
    - *install-dependencies
    - name: Build
      run: npm run all